# Generated by Django 3.2.7 on 2021-09-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=64)),
                ('semester', models.PositiveIntegerField()),
                ('academic_year', models.PositiveIntegerField()),
                ('limit', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
