# Generated by Django 3.2.7 on 2021-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=10)),
                ('grade', models.FloatField()),
                ('years', models.PositiveIntegerField()),
                ('enrollment', models.ManyToManyField(blank=True, to='Register.Course')),
            ],
        ),
    ]
