# Generated by Django 3.2.7 on 2021-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.ManyToManyField(blank=True, related_name='member', to='Register.Course'),
        ),
    ]
