# Generated by Django 3.2.7 on 2021-09-14 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Register', '0003_alter_student_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment',
            field=models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
