# Generated by Django 3.2.7 on 2021-09-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Register', '0004_auto_20210914_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('grade', models.FloatField()),
                ('years', models.PositiveIntegerField()),
                ('enrollment', models.ManyToManyField(blank=True, related_name='member', to='Register.Course')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
