# Generated by Django 3.2.7 on 2021-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment',
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.ManyToManyField(blank=True, related_name='enroll', to='Register.Course'),
        ),
    ]
