# Generated by Django 3.2.7 on 2021-09-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_auto_20210915_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
